<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
    <PackageReference Include="bunit" Version="2.9.0" PrivateAssets="all" />
    <ProjectReference Include="..\FleetDashboard.Shared\FleetDashboard.Shared.csproj" />
    <ProjectReference Include="..\FleetDashboard.Client\FleetDashboard.Client.csproj" />
    <ProjectReference Include="..\FleetDashboard.Server\FleetDashboard.Server.csproj" />
  </ItemGroup>

</Project>
